---
build_from:
  aarch64: ghcr.io/hassio-addons/base:18.1.2
  amd64: ghcr.io/hassio-addons/base:18.1.2
  armv7: ghcr.io/hassio-addons/base:18.1.2
#codenotary:
#  signer: lucio.tarantino@gmail.com
#  base_image: codenotary@frenck.dev
#cosign:
#  #base_identity: https://github.com/home-assistant/builder/.*
#  identity: https://github.com/dianlight/hassio-addons/.*
args:
  SRAT_VERSION: "2025.9.0-dev.3"
