---
build_from:
  aarch64: ghcr.io/hassio-addons/base:18.0.0
  amd64: ghcr.io/hassio-addons/base:18.0.0
  armv7: ghcr.io/hassio-addons/base:18.0.0
#codenotary:
#  signer: lucio.tarantino@gmail.com
#  base_image: codenotary@frenck.dev
#cosign:
#  #base_identity: https://github.com/home-assistant/builder/.*
#  identity: https://github.com/dianlight/hassio-addons/.*
args:
  SRAT_VERSION: "2025.6.9-dev.9"
