---
build_from:
  aarch64: ghcr.io/hassio-addons/base:18.2.0
  amd64: ghcr.io/hassio-addons/base:18.2.0
  armv7: ghcr.io/hassio-addons/base:18.2.0
#codenotary:
#  signer: lucio.tarantino@gmail.com
#  base_image: codenotary@frenck.dev
#cosign:
#  #base_identity: https://github.com/home-assistant/builder/.*
#  identity: https://github.com/dianlight/hassio-addons/.*
args:
  CLI_VERSION: "4.37.0"
  SRAT_VERSION: "2025.9.0-dev.4"
  SAMBA_VERSION: "distribution" #"4.23.1" # Use "distribution" to use precompiled packages
