---
build_from:
  aarch64: ghcr.io/hassio-addons/base:19.0.0
  amd64: ghcr.io/hassio-addons/base:19.0.0
#cosign:
#  #base_identity: https://github.com/home-assistant/builder/.*
#  identity: https://github.com/dianlight/hassio-addons/.*
args:
  CLI_VERSION: "4.42.0"
  SRAT_VERSION: "2025.10.0-dev.1"
  SAMBA_VERSION: "distribution" #"4.23.1" # Use "distribution" to use precompiled packages
