---
build_from:
  aarch64: ghcr.io/hassio-addons/base:17.0.0
  amd64: ghcr.io/hassio-addons/base:17.0.0
  armv7: ghcr.io/hassio-addons/base:17.0.0
codenotary:
  signer: lucio.tarantino@gmail.com
  base_image: codenotary@frenck.dev
cosign:
  #base_identity: https://github.com/home-assistant/builder/.*
  identity: https://github.com/dianlight/hassio-addons/.*
args:
  #  HDDTEMP_VERSION: "0.3-beta15"
  SRAT_VERSION: "v2024.12.0"
