---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.0.1
  amd64: ghcr.io/hassio-addons/base:14.0.1
  armhf: ghcr.io/hassio-addons/base:14.0.1
  armv7: ghcr.io/hassio-addons/base:14.0.1
  i386: ghcr.io/hassio-addons/base:14.0.1
codenotary:
  signer: dan.veitch@gmail.com
  base_image: codenotary@frenck.dev
args:
  HDDTEMP_VERSION: "0.3-beta15"
