---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.19
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.19
#  armv7: ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.19
#codenotary:
#  signer: lucio.tarantino@gmail.com
#  base_image: codenotary@frenck.dev
cosign:
  base_identity: https://github.com/home-assistant/docker-base/.*
  identity: https://github.com/dianlight/hassio-addons/.*
args:
  PYTHON_VERSION: 3.12.2
