---
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.6
  amd64: ghcr.io/hassio-addons/base:15.0.6
  armv7: ghcr.io/hassio-addons/base:15.0.6
#codenotary:
#  signer: lucio.tarantino@gmail.com
#  base_image: codenotary@frenck.dev
args:
  PYTHON_VERSION: 3.12.2