---
name: BeSim
version: 0.0.1
slug: besim
description: A simulator for the cloud server the BeSMART thermostat/wifi box connects to.
url: https://github.com/dianlight/hassio-addons/tree/master/besim
codenotary: lucio.tarantino@gmail.com
arch:
  - armv7
  - aarch64
  - amd64
startup: system
boot: auto
init: false
hassio_api: true
#hassio_role: admin
#host_network: true
#map:
#  - homeassistant_config:rw
#  - addon_config:rw
#  - ssl:rw
#  - all_addon_configs:rw
#  - addons:rw
#  - share:rw
#  - backup:rw
#  - media:rw
options:
  updateonboot: true
schema:
  updateonboot: bool?
#  workgroup: str
#  username: str
#  password: password
#  automount: bool?
#  moredisks:
#    - str
#  mountoptions:
#    - str
#  available_disks_log: bool?
#  medialibrary:
#    enable: bool?
#    ssh_private_key: password?
#  allow_hosts:
#    - str
#    - str
#  veto_files:
#  compatibility_mode: bool?
#  recyle_bin_enabled: bool?
#  wsdd2: bool?
#  hdd_idle_seconds: int(0,)?
#  enable_smart: bool?
#  mqtt_nexgen_entities: bool?
#  mqtt_enable: bool?
#  mqtt_host: str?
#  mqtt_username: str?
#  mqtt_password: password?
#  mqtt_port: str?
#  mqtt_topic: str?
#  autodiscovery:
#    disable_discovery: bool?
#    disable_persistent: bool?
#    disable_autoremove: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?

image: dianlight/{arch}-addon-besim
ports:
  6199/udp: 6199
  80/tcp: 80
ports_description:
  6199/udp: "api.besmart-home.com:6199 (udp)"
  80/tcp: "api.besmart-home.com:80 (tcp, http get) and www.cloudwarm.com:80 (tcp, http post)"
#services:
#  - mqtt:want
#udev: true
#host_dbus: true
#kernel_modules: true
#privileged:
#  - SYS_ADMIN
#  - SYS_RAWIO
#  - SYS_RESOURCE
#  - SYS_MODULE
#full_access: true
#devicetree: false
apparmor: true
#host_ipc: true
#advanced: true
homeassistant: 2023.11.0
backup: hot
#auth_api: true
