name: Docker Image CI - Build Release.

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 📽️ Extract dev branch project name
        shell: bash
        run: |
           FULL_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/release/}}"
           echo "full_name=${FULL_NAME} >> $GITHUB_OUTPUT
           echo "name=${FULL_NAME%%_*}" >> $GITHUB_OUTPUT
        id: extract_project

      - name: ✍🏼 version ${{ steps.extract_project.outputs.name }}
        id: version_get
        uses: endaft/action-yamler@v1.1.1
        with:
          file: ./${{ steps.extract_project.outputs.name }}/config.yaml
          path: version
          get: true

      - name: 📰 Publish ${{ steps.extract_project.outputs.name }} Addon ${{ steps.version_set.outputs.value_new }}
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --docker-hub-check \
            --target ${{ steps.extract_project.outputs.name }} \
            --docker-hub dianlight \   
            --cosign        

      - name: pull-request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        shell: bash
        run: |
          gh pr create --title "Releasing ${{ github.ref }} into master" --body ":crown: *An automated PR*"